//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Bridge/Input/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""LeftHand"",
            ""id"": ""ee8d9e72-4df2-4e1a-aed6-cacd945ceef1"",
            ""actions"": [
                {
                    ""name"": ""LF1"",
                    ""type"": ""Value"",
                    ""id"": ""325bad5d-a3a4-496a-843b-e8d065d5f678"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LF2"",
                    ""type"": ""Value"",
                    ""id"": ""532978d6-e785-4fd1-a193-c7ee32fdfce5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LF3"",
                    ""type"": ""Value"",
                    ""id"": ""689f5bb1-11c7-477a-b4fa-01c7b21e2465"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LF4"",
                    ""type"": ""Value"",
                    ""id"": ""468c2db9-27ef-4dd2-84f8-d894b5e973f8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LF5"",
                    ""type"": ""Value"",
                    ""id"": ""afc14df0-5957-4a8d-99f4-b780db0ae7fc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""T-G"",
                    ""id"": ""40fbc6df-f546-4d97-aca6-4b1df467aa4b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LF1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""252d492e-adb8-4521-9fd7-4b93769e107e"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Simulation"",
                    ""action"": ""LF1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4269f6db-c2b3-4465-8db3-df753bc06477"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Simulation"",
                    ""action"": ""LF1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""R-F"",
                    ""id"": ""e18e48ee-c9be-4095-a8bb-be33b32eb609"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LF2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""db4ccc1f-79bc-456c-ba09-fdcd435c8de3"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Simulation"",
                    ""action"": ""LF2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5444dc3e-e4da-4e70-ba6a-bf832a23122e"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Simulation"",
                    ""action"": ""LF2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""E-D"",
                    ""id"": ""df447156-db85-4ad9-8867-dff06f4c256d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LF3"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e7373a17-0b22-443d-a53b-92fd0d65f108"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Simulation"",
                    ""action"": ""LF3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""400153b8-c5ba-41c4-ae48-ea691be96a1b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Simulation"",
                    ""action"": ""LF3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""W-S"",
                    ""id"": ""67af1223-c7ee-429e-a388-60b8d15a721d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LF4"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a7f5d1d5-6a46-4189-ab94-2c22ff453020"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Simulation"",
                    ""action"": ""LF4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d595e41e-fa96-48fc-a392-3a7ee4da0890"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Simulation"",
                    ""action"": ""LF4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Q-A"",
                    ""id"": ""d352b536-f61f-442a-9501-51ed679ee1a6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LF5"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9a0f20be-ba71-4cd3-8e63-793810b93ac2"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Simulation"",
                    ""action"": ""LF5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4411492c-14bf-4bf6-afe4-ad365aac642c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Simulation"",
                    ""action"": ""LF5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""RightHand"",
            ""id"": ""b5087eb8-6373-4fd1-823e-1385ad00b1ce"",
            ""actions"": [
                {
                    ""name"": ""RF1"",
                    ""type"": ""Value"",
                    ""id"": ""040720a1-7b7a-4f0f-ab31-537c89458065"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RF2"",
                    ""type"": ""Value"",
                    ""id"": ""00923c2f-1a9a-428c-aed6-9a4fa2ad8e63"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RF3"",
                    ""type"": ""Value"",
                    ""id"": ""eab0cf48-d000-4b8d-acd0-35acc5d9749a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RF4"",
                    ""type"": ""Value"",
                    ""id"": ""c7190e66-87b0-44eb-878e-f3c410e1ad42"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RF5"",
                    ""type"": ""Value"",
                    ""id"": ""8507d29b-8d8c-4996-9af8-0e232c3a6ae2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Y-H"",
                    ""id"": ""5901b3e3-70bc-420d-8915-bba0ef07092e"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RF1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""e2b3cf73-3ee1-4513-bace-7e1888f430df"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Simulation"",
                    ""action"": ""RF1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""7770e8ab-1214-4989-ac6e-5c1a91e715ff"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Simulation"",
                    ""action"": ""RF1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""U-J"",
                    ""id"": ""dc30054f-e1fe-46a1-9956-4f99800fcdd8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RF2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""fe1362a7-e839-4b30-a004-f805d8cd4c06"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RF2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d1893103-cae0-48f8-865d-d1d4372c024e"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RF2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""I-K"",
                    ""id"": ""767d0980-17dd-48bd-9993-21f3900c915c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RF3"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4b189c64-01aa-443a-9bea-6a1878c280a8"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RF3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1ace201b-b970-4da7-b3ec-2dba80527594"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RF3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""O-l"",
                    ""id"": ""22360c7d-adfc-4e83-9d8f-ced4a7eabf4c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RF4"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""92ea4db9-d54b-4398-9423-2a0f755ca373"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RF4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""dc4fad04-a7ad-4e3e-8a75-2afb42e5ef40"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RF4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""P-:"",
                    ""id"": ""409bf3c4-0ec1-4193-8e6b-c8c3ebc5db2e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RF5"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""54ff5600-f019-45b0-9b64-6b5005a1cc27"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RF5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f95f1511-29cb-446f-b0ef-985fdaa7a54a"",
                    ""path"": ""<Keyboard>/semicolon"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RF5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Simulation"",
            ""bindingGroup"": ""Simulation"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // LeftHand
        m_LeftHand = asset.FindActionMap("LeftHand", throwIfNotFound: true);
        m_LeftHand_LF1 = m_LeftHand.FindAction("LF1", throwIfNotFound: true);
        m_LeftHand_LF2 = m_LeftHand.FindAction("LF2", throwIfNotFound: true);
        m_LeftHand_LF3 = m_LeftHand.FindAction("LF3", throwIfNotFound: true);
        m_LeftHand_LF4 = m_LeftHand.FindAction("LF4", throwIfNotFound: true);
        m_LeftHand_LF5 = m_LeftHand.FindAction("LF5", throwIfNotFound: true);
        // RightHand
        m_RightHand = asset.FindActionMap("RightHand", throwIfNotFound: true);
        m_RightHand_RF1 = m_RightHand.FindAction("RF1", throwIfNotFound: true);
        m_RightHand_RF2 = m_RightHand.FindAction("RF2", throwIfNotFound: true);
        m_RightHand_RF3 = m_RightHand.FindAction("RF3", throwIfNotFound: true);
        m_RightHand_RF4 = m_RightHand.FindAction("RF4", throwIfNotFound: true);
        m_RightHand_RF5 = m_RightHand.FindAction("RF5", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // LeftHand
    private readonly InputActionMap m_LeftHand;
    private List<ILeftHandActions> m_LeftHandActionsCallbackInterfaces = new List<ILeftHandActions>();
    private readonly InputAction m_LeftHand_LF1;
    private readonly InputAction m_LeftHand_LF2;
    private readonly InputAction m_LeftHand_LF3;
    private readonly InputAction m_LeftHand_LF4;
    private readonly InputAction m_LeftHand_LF5;
    public struct LeftHandActions
    {
        private @Controls m_Wrapper;
        public LeftHandActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @LF1 => m_Wrapper.m_LeftHand_LF1;
        public InputAction @LF2 => m_Wrapper.m_LeftHand_LF2;
        public InputAction @LF3 => m_Wrapper.m_LeftHand_LF3;
        public InputAction @LF4 => m_Wrapper.m_LeftHand_LF4;
        public InputAction @LF5 => m_Wrapper.m_LeftHand_LF5;
        public InputActionMap Get() { return m_Wrapper.m_LeftHand; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LeftHandActions set) { return set.Get(); }
        public void AddCallbacks(ILeftHandActions instance)
        {
            if (instance == null || m_Wrapper.m_LeftHandActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LeftHandActionsCallbackInterfaces.Add(instance);
            @LF1.started += instance.OnLF1;
            @LF1.performed += instance.OnLF1;
            @LF1.canceled += instance.OnLF1;
            @LF2.started += instance.OnLF2;
            @LF2.performed += instance.OnLF2;
            @LF2.canceled += instance.OnLF2;
            @LF3.started += instance.OnLF3;
            @LF3.performed += instance.OnLF3;
            @LF3.canceled += instance.OnLF3;
            @LF4.started += instance.OnLF4;
            @LF4.performed += instance.OnLF4;
            @LF4.canceled += instance.OnLF4;
            @LF5.started += instance.OnLF5;
            @LF5.performed += instance.OnLF5;
            @LF5.canceled += instance.OnLF5;
        }

        private void UnregisterCallbacks(ILeftHandActions instance)
        {
            @LF1.started -= instance.OnLF1;
            @LF1.performed -= instance.OnLF1;
            @LF1.canceled -= instance.OnLF1;
            @LF2.started -= instance.OnLF2;
            @LF2.performed -= instance.OnLF2;
            @LF2.canceled -= instance.OnLF2;
            @LF3.started -= instance.OnLF3;
            @LF3.performed -= instance.OnLF3;
            @LF3.canceled -= instance.OnLF3;
            @LF4.started -= instance.OnLF4;
            @LF4.performed -= instance.OnLF4;
            @LF4.canceled -= instance.OnLF4;
            @LF5.started -= instance.OnLF5;
            @LF5.performed -= instance.OnLF5;
            @LF5.canceled -= instance.OnLF5;
        }

        public void RemoveCallbacks(ILeftHandActions instance)
        {
            if (m_Wrapper.m_LeftHandActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILeftHandActions instance)
        {
            foreach (var item in m_Wrapper.m_LeftHandActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LeftHandActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LeftHandActions @LeftHand => new LeftHandActions(this);

    // RightHand
    private readonly InputActionMap m_RightHand;
    private List<IRightHandActions> m_RightHandActionsCallbackInterfaces = new List<IRightHandActions>();
    private readonly InputAction m_RightHand_RF1;
    private readonly InputAction m_RightHand_RF2;
    private readonly InputAction m_RightHand_RF3;
    private readonly InputAction m_RightHand_RF4;
    private readonly InputAction m_RightHand_RF5;
    public struct RightHandActions
    {
        private @Controls m_Wrapper;
        public RightHandActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @RF1 => m_Wrapper.m_RightHand_RF1;
        public InputAction @RF2 => m_Wrapper.m_RightHand_RF2;
        public InputAction @RF3 => m_Wrapper.m_RightHand_RF3;
        public InputAction @RF4 => m_Wrapper.m_RightHand_RF4;
        public InputAction @RF5 => m_Wrapper.m_RightHand_RF5;
        public InputActionMap Get() { return m_Wrapper.m_RightHand; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RightHandActions set) { return set.Get(); }
        public void AddCallbacks(IRightHandActions instance)
        {
            if (instance == null || m_Wrapper.m_RightHandActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RightHandActionsCallbackInterfaces.Add(instance);
            @RF1.started += instance.OnRF1;
            @RF1.performed += instance.OnRF1;
            @RF1.canceled += instance.OnRF1;
            @RF2.started += instance.OnRF2;
            @RF2.performed += instance.OnRF2;
            @RF2.canceled += instance.OnRF2;
            @RF3.started += instance.OnRF3;
            @RF3.performed += instance.OnRF3;
            @RF3.canceled += instance.OnRF3;
            @RF4.started += instance.OnRF4;
            @RF4.performed += instance.OnRF4;
            @RF4.canceled += instance.OnRF4;
            @RF5.started += instance.OnRF5;
            @RF5.performed += instance.OnRF5;
            @RF5.canceled += instance.OnRF5;
        }

        private void UnregisterCallbacks(IRightHandActions instance)
        {
            @RF1.started -= instance.OnRF1;
            @RF1.performed -= instance.OnRF1;
            @RF1.canceled -= instance.OnRF1;
            @RF2.started -= instance.OnRF2;
            @RF2.performed -= instance.OnRF2;
            @RF2.canceled -= instance.OnRF2;
            @RF3.started -= instance.OnRF3;
            @RF3.performed -= instance.OnRF3;
            @RF3.canceled -= instance.OnRF3;
            @RF4.started -= instance.OnRF4;
            @RF4.performed -= instance.OnRF4;
            @RF4.canceled -= instance.OnRF4;
            @RF5.started -= instance.OnRF5;
            @RF5.performed -= instance.OnRF5;
            @RF5.canceled -= instance.OnRF5;
        }

        public void RemoveCallbacks(IRightHandActions instance)
        {
            if (m_Wrapper.m_RightHandActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRightHandActions instance)
        {
            foreach (var item in m_Wrapper.m_RightHandActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RightHandActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RightHandActions @RightHand => new RightHandActions(this);
    private int m_SimulationSchemeIndex = -1;
    public InputControlScheme SimulationScheme
    {
        get
        {
            if (m_SimulationSchemeIndex == -1) m_SimulationSchemeIndex = asset.FindControlSchemeIndex("Simulation");
            return asset.controlSchemes[m_SimulationSchemeIndex];
        }
    }
    public interface ILeftHandActions
    {
        void OnLF1(InputAction.CallbackContext context);
        void OnLF2(InputAction.CallbackContext context);
        void OnLF3(InputAction.CallbackContext context);
        void OnLF4(InputAction.CallbackContext context);
        void OnLF5(InputAction.CallbackContext context);
    }
    public interface IRightHandActions
    {
        void OnRF1(InputAction.CallbackContext context);
        void OnRF2(InputAction.CallbackContext context);
        void OnRF3(InputAction.CallbackContext context);
        void OnRF4(InputAction.CallbackContext context);
        void OnRF5(InputAction.CallbackContext context);
    }
}
